Enable CI build GitHub Action to run on pull requests on a fork
Shopify/shopify_app pull request #1201
Opened 2021-03-04 15:06 UTC by andyw8

This wasn't running for external contributors, e.g. https://github.com/Shopify/shopify_app/pull/1187

2021-03-04 15:16 UTC, mllemango approved these changes

2021-03-04 16:27 UTC, Paulinakhew requested changes

2021-03-04 16:27 UTC, Paulinakhew commented on .github/workflows/build.yml
> +    branches: [ master ]
```suggestion
  [push, pull_request]:
    branches: 
      - master
```

Syntax taken from [github docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows). We can put the duplicates in a list and put `master` by itself

2021-03-04 16:57 UTC, Paulinakhew commented on .github/workflows/build.yml
> +    branches: [ master ]
if we don't want to run CI twice, we can do this
```yaml
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
```

2021-03-12 14:57 UTC, andyw8 commented
Let's not worry too much about running CI twice for the moment.

2021-03-12 15:02 UTC, paulomarg approved these changes
Agreed, let's run it twice for now and we can change it later.

2021-03-12 15:59 UTC, merged