Support App Bridge 2.0 in shopify_app
Shopify/shopify_app pull request #1241
Opened 2021-04-01 19:52 UTC by rezaansyed

### What this PR does

Support App Bridge 2.0

### Reviewer's guide to testing

- Import local version of this branch to new app
- Ensure that app runs as expected in Admin

### Things to focus on

Ensure migration strategy is followed as per the [guide](https://shopify.dev/tutorials/migrate-your-app-to-app-bridge-2).

### Checklist

Before submitting the PR, please consider if any of the following are needed:

- [x] Update `CHANGELOG.md` if the changes would impact users
- [x] Update `README.md`, if appropriate.
- [x] Update any relevant pages in `/docs`, if necessary
- [x] For security fixes, the [Disclosure Policy](https://github.com/Shopify/shopify_app/blob/master/SECURITY.md#disclosure-policy) must be followed.

2021-04-01 20:09 UTC, hannachen approved these changes
Looks good to me 👍

2021-04-05 13:06 UTC, paulomarg requested changes
I've tried this out now, and I got the following error:
```
message: "APP::ERROR::INVALID_CONFIG: host must be provided"
name: "AppBridgeError"
type: "APP::ERROR::INVALID_CONFIG"
```

It seems that coming back from OAuth, we're lacking the `host` parameter and thus we can't load App Bridge properly.

2021-04-05 14:08 UTC, rezaansyed commented
> I've tried this out now, and I got the following error:
> 
> ```
> message: "APP::ERROR::INVALID_CONFIG: host must be provided"
> name: "AppBridgeError"
> type: "APP::ERROR::INVALID_CONFIG"
> ```
> 
> It seems that coming back from OAuth, we're lacking the `host` parameter and thus we can't load App Bridge properly.

Noticing that on my end too. It has to do with the `HomeController` not having the `host` param passed in and can't initialize App Bridge at the top level. Is there any way for us to know of the host during OAuth @hannachen?

2021-04-05 14:13 UTC, NabeelAhsen commented
If the `host` parameter is part of the callback URL sent by Shopify to the app, step 3 of this doc might be outdated: https://shopify.dev/tutorials/authenticate-with-oauth#step-3-confirm-installation

Is this where the `host` parameter is initially supposed to come from?

2021-04-05 14:15 UTC, rezaansyed commented
> If the `host` parameter is part of the callback URL sent by Shopify to the app, step 3 of this doc might be outdated: https://shopify.dev/tutorials/authenticate-with-oauth#step-3-confirm-installation
> 
> Is this where the `host` parameter is initially supposed to come from?

It's not part of the callback controller. The failure happens when hitting the home controller at the top level right after the callback controller though.

2021-04-05 14:19 UTC, paulomarg commented
Should we be including the host in the redirect URL when we begin OAuth?

2021-04-14 15:50 UTC, NabeelAhsen commented on lib/shopify_app/controller_concerns/login_protection.rb
> +    rescue ShopifyDomainNotFound, ShopifyHostNotFound
Things I'm unsure about here:
- Right now, there are two known places that use `return_address` in this code base. Is raising when `host` isn't found the the correct move here?
- What other tests are affected by this?

2021-04-14 15:51 UTC, NabeelAhsen commented
> Should we be including the host in the redirect URL when we begin OAuth? That way, we'd be able to reference it when coming back.

This `host` param comes from Shopify's generated URLs, so we'd only be aware of them on OAuth return

2021-04-15 13:56 UTC, paulomarg approved these changes
🎩 ed again, OAuth worked correctly for me now.

2021-04-15 13:56 UTC, paulomarg commented on lib/shopify_app/controller_concerns/login_protection.rb
> +    rescue ShopifyDomainNotFound, ShopifyHostNotFound
Considering we currently throw a similar exception for the domain, it makes sense to me to continue to throw here.

2021-04-19 18:07 UTC, merged

2021-06-29 16:46 UTC, asecondwill commented
This does not work when trying to update a JWT Turbo Example app.  Please can you test with that and provide instructions @NabeelAhsen

2021-06-29 17:11 UTC, asecondwill commented
Probably worth noting,  host is not passed back in the params @paulomarg